======Starting Image Build on Compute======
The run ID for the image build on compute is imgbldrun_9d5fdd8
Additional logs for the run: https://ml.azure.com/experiments/id/prepare_image/runs/imgbldrun_9d5fdd8?wsid=/subscriptions/fb992ba5-7179-418e-8b18-65a7e81d5cc1/resourcegroups/nanovlm-rg/workspaces/nanovlm-workspace&tid=0fabc88a-2565-420d-9dfe-64f803897c56
2025-07-03T22:10:56: Logging into Docker registry: cc24132d31ea49dd91af126dcd6135ae.azurecr.io
2025-07-03T22:10:56: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
2025-07-03T22:10:56: Login Succeeded

2025-07-03T22:10:56: WARNING! Your credentials are stored unencrypted in '/root/.docker/config.json'.
2025-07-03T22:10:56: Configure a credential helper to remove this warning. See
2025-07-03T22:10:56: https://docs.docker.com/go/credential-store/



2025-07-03T22:10:56: Running: ['docker', 'build', '-f', './Dockerfile', '.', '-t', 'cc24132d31ea49dd91af126dcd6135ae.azurecr.io/azureml/azureml_4e3b2f750dacba672ea924b273bb2c57', '-t', 'cc24132d31ea49dd91af126dcd6135ae.azurecr.io/azureml/azureml_4e3b2f750dacba672ea924b273bb2c57:2']
2025-07-03T22:10:57: #0 building with "default" instance using docker driver

2025-07-03T22:10:57: #1 [internal] load build definition from Dockerfile
2025-07-03T22:10:57: #1 transferring dockerfile:
2025-07-03T22:10:57: #1 transferring dockerfile: 1.66kB done
2025-07-03T22:10:57: #1 DONE 0.2s

2025-07-03T22:10:57: #2 [internal] load .dockerignore
2025-07-03T22:10:57: #2 transferring context: 2B done
2025-07-03T22:10:57: #2 DONE 0.2s

2025-07-03T22:10:57: #3 [internal] load metadata for mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu20.04:latest
2025-07-03T22:10:57: #3 ERROR: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu20.04:latest: not found
2025-07-03T22:10:57: ------
2025-07-03T22:10:57:  > [internal] load metadata for mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu20.04:latest:
2025-07-03T22:10:57: ------
2025-07-03T22:10:57: Dockerfile:1
2025-07-03T22:10:57: --------------------
2025-07-03T22:10:57:    1 | >>> FROM mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu20.04:latest
2025-07-03T22:10:57:    2 |     
2025-07-03T22:10:57:    3 |     # Install Python 3.12
2025-07-03T22:10:57: --------------------
2025-07-03T22:10:57: ERROR: failed to solve: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu20.04:latest: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu20.04:latest: not found


2025-07-03T22:10:57: CalledProcessError(1, ['docker', 'build', '-f', './Dockerfile', '.', '-t', 'cc24132d31ea49dd91af126dcd6135ae.azurecr.io/azureml/azureml_4e3b2f750dacba672ea924b273bb2c57', '-t', 'cc24132d31ea49dd91af126dcd6135ae.azurecr.io/azureml/azureml_4e3b2f750dacba672ea924b273bb2c57:2'])

2025-07-03T22:10:57: Building docker image failed with exit code: 1

2025-07-03T22:10:57: Logging out of Docker registry: cc24132d31ea49dd91af126dcd6135ae.azurecr.io
2025-07-03T22:10:57: Removing login credentials for https://index.docker.io/v1/


2025-07-03T22:10:57: Traceback (most recent call last):
  File "/mnt/azureml/cr/j/65f517d4b86041af93377ec3e64b5f14/exe/wd/docker_utilities.py", line 152, in _docker_build_or_error
    docker_execute_function(docker_command, build_command, print_command_args=True)
  File "/mnt/azureml/cr/j/65f517d4b86041af93377ec3e64b5f14/exe/wd/docker_utilities.py", line 23, in docker_execute_function
    return killable_subprocess.check_call(command_args, *popen_args,
  File "/mnt/azureml/cr/j/65f517d4b86041af93377ec3e64b5f14/exe/wd/killable_subprocess.py", line 261, in check_call
    raise subprocess.CalledProcessError(process.returncode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-f', './Dockerfile', '.', '-t', 'cc24132d31ea49dd91af126dcd6135ae.azurecr.io/azureml/azureml_4e3b2f750dacba672ea924b273bb2c57', '-t', 'cc24132d31ea49dd91af126dcd6135ae.azurecr.io/azureml/azureml_4e3b2f750dacba672ea924b273bb2c57:2']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 162, in <module>
    docker_utilities._docker_build_or_error(
  File "/mnt/azureml/cr/j/65f517d4b86041af93377ec3e64b5f14/exe/wd/docker_utilities.py", line 156, in _docker_build_or_error
    _write_error_and_exit(error_msg, error_file_path=error_file_path)
  File "/mnt/azureml/cr/j/65f517d4b86041af93377ec3e64b5f14/exe/wd/docker_utilities.py", line 217, in _write_error_and_exit
    sys.exit(1)
SystemExit: 1

